spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/activity
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: activity-service
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/cutomers
    mission-url: http://localhost:8222/api/v1/missions
    payment-url: http://localhost:8222/api/v1/payments
    collaborator-url: http://localhost:8222/api/v1/collaborators
    employee-url: http://localhost:8222/api/v1/employees
