spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/api/v1/customers/**
        - id: activity-service
          uri: ${ACTIVITY_SERVICE_URL:http://localhost:8070}
          predicates:
            - Path=/api/v1/activities/**
        - id: mission-service
          uri: ${MISSION_SERVICE_URL:http://localhost:8050}
          predicates:
            - Path=/api/v1/missions/**
        - id: stuff-service
          uri: ${STUFF_SERVICE_URL:http://localhost:8060}
          predicates:
            - Path=/api/v1/stuff/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8040}
          predicates:
            - Path=/api/v1/payments/**
server:
  port: 8222
