spring:
  application:
    name: stuff-service
  config:
    import: optional:configserver:http://localhost:8888

# App Properties
stuff:
  app:
    jwtCookieName: acensi
    jwtSecret: ======================Acensi=Spring===========================
    jwtExpirationMs: 86400000